### ISSUE TITLE
Encrypt Nutzdaten file for transmission

### ISSUE THREAD

**Issue by michaelkamphausen** [coop-care/paid#20]

**Comment by westnordost** [comment]
I compiled this table from the information in this document (page 4ff):
https://gkv-datenaustausch.de/media/dokumente/standards_und_normen/technische_spezifikationen/Anlage_16.pdf

It looks like WebCrypto can be used for signing and encrypting the data. What the GKV uses in terms of encryption is quite standard.

<table>
<tr><th></th><th>old<br/>(supported max until end 2022)</th><th>new</th></tr>
<tr>
	<td><b>Hash algorithm</b></td>
	<td colspan="2">SHA-256</td>
</tr>
<tr>
	<td><b>Signature algorithm</b><br/>
	(<a href="https://developer.mozilla.org/en-US/docs/Web/API/SubtleCrypto/sign">documentation</a>)</td>
	<td><b>RSASSA PKCS#1 v1.5</b></td>
	<td>
		<b>RSASSA-PSS (RFC 8017)*</b><br/>
		publicExponent: 65537</td>
</tr>
<tr>
	<td><b>Symetric encryption algorithm</b><br/>
	(<a href="https://developer.mozilla.org/en-US/docs/Web/API/SubtleCrypto/encrypt">documentation</a>)
	</td>
	<td colspan="2">AES-CBC</td>
</tr>
<tr>
	<td><b>Key generation encryption algorithm</b><br/>
	(<a href="https://developer.mozilla.org/en-US/docs/Web/API/SubtleCrypto/generateKey">documentation</a>)
	</td>
	<td>
		<b>RSASSA PKCS#1 v1.5</b><br />
		modulus length: 2048bit<br/>
		hash: SHA-256<br />
		public exponent: 65537<br />
	</td>
	<td>
		<b>RSA-OAEP</b><br />
		modulus length: <b>4096bit</b><br/>
		hash: SHA-256<br />
		public exponent: 65537<br />
	</td>
</tr>
<tr>
	<td><b>Subject public key algorithm</b></td>
	<td colspan="2">rsaEncryption???</td>
</tr>
</table>

The documentation links lead to the MDN documentation on WebCrypto.

Helpful link: <a href="https://github.com/diafygi/webcrypto-examples/#rsa-pss">WebCrypto examples</a>

* Above linked document from GKV-Datenaustausch refers to RSASSA-PSS <a href="https://datatracker.ietf.org/doc/html/rfc8017#section-8.1">as defined in RFC8017</a>. The WebCrypto API documentation <a href="https://developer.mozilla.org/en-US/docs/Web/API/SubtleCrypto/sign#rsa-pss">refers to RSA-PSS</a> <a href="https://datatracker.ietf.org/doc/html/rfc3447#section-8.1">as defined in RFC3447</a>. RFC3447 supercedes RFC8017, and also, RFC3447 does actually not mention "RSA-PSS" as a section header but RSASSA-PSS as well. So, I am pretty sure that "RSA-PSS" is just a synonym/abbreviation for RSASSA-PSS.

**Comment by westnordost** [comment]
Ok, turns out that all Datenannahmestellen already have a new key. Some even don't have an old key anymore.

**Comment by michaelkamphausen** [comment]
Done
