### ISSUE TITLE
Clarify spurious Kostenträgerdatei data for BKK VBU/West and Ost

### ISSUE THREAD

**Issue by westnordost** [coop-care/paid#25]
Pasing BK05Q221.ke1 results in the following warnings
<pre>
message 303 - skipped invalid VKG 11: Links to data acceptance office that does not accept data
message 303 - skipped invalid VKG 12: Links to data acceptance office that does not accept data
message 303 - skipped invalid VKG 13: Links to data acceptance office that does not accept data
message 303 - skipped invalid VKG 14: Links to data acceptance office that does not accept data
message 303 - skipped invalid VKG 15: Links to data acceptance office that does not accept data
message 303 - skipped invalid VKG 16: Links to data acceptance office that does not accept data
message 303 - skipped invalid VKG 17: Links to data acceptance office that does not accept data
message 303 - skipped invalid VKG 18: Links to data acceptance office that does not accept data
message 303 - skipped invalid VKG 20: Links to data acceptance office that does not accept data
message 303 - skipped invalid VKG 21: Links to data acceptance office that does not accept data
message 303 - skipped invalid VKG 22: Links to data acceptance office that does not accept data
message 303 - skipped invalid VKG 23: Links to data acceptance office that does not accept data
message 303 - skipped invalid VKG 24: Links to data acceptance office that does not accept data
message 303 - skipped invalid VKG 25: Links to data acceptance office that does not accept data
message 303 - skipped invalid VKG 26: Links to data acceptance office that does not accept data
message 303 - skipped invalid VKG 27: Links to data acceptance office that does not accept data
message 304 - skipped invalid VKG 11: Links to data acceptance office that does not accept data
message 304 - skipped invalid VKG 12: Links to data acceptance office that does not accept data
message 304 - skipped invalid VKG 13: Links to data acceptance office that does not accept data
message 304 - skipped invalid VKG 14: Links to data acceptance office that does not accept data
message 304 - skipped invalid VKG 15: Links to data acceptance office that does not accept data
message 304 - skipped invalid VKG 16: Links to data acceptance office that does not accept data
message 304 - skipped invalid VKG 17: Links to data acceptance office that does not accept data
message 304 - skipped invalid VKG 18: Links to data acceptance office that does not accept data
message 304 - skipped invalid VKG 20: Links to data acceptance office that does not accept data
message 304 - skipped invalid VKG 21: Links to data acceptance office that does not accept data
message 304 - skipped invalid VKG 22: Links to data acceptance office that does not accept data
message 304 - skipped invalid VKG 23: Links to data acceptance office that does not accept data
message 304 - skipped invalid VKG 24: Links to data acceptance office that does not accept data
message 304 - skipped invalid VKG 25: Links to data acceptance office that does not accept data
message 304 - skipped invalid VKG 26: Links to data acceptance office that does not accept data
message 304 - skipped invalid VKG 27: Links to data acceptance office that does not accept data
</pre>

for these lines:
<pre>
VKG+03+109723913+5++28++++55'
VKG+03+109723913+5++28++++56'
VKG+03+109723913+5++28++++57'
VKG+03+109723913+5++28++++63'
VKG+03+109723913+5++28++++66'
VKG+03+109723913+5++28++++67'
VKG+03+109723913+5++28++++69'
VKG+03+109723913+5++28++++90'
</pre>
(and more).

They all have in common that the type of link ("data acceptance office with decryption capacity") and the type of data acceptance ("paper receipts") seem to contradict each other.

Currently, these links that are deemed as invalid are dropped. But maybe this is a misunderstanding.

**Comment by westnordost** [comment]
The Kostenträger file does not list a contact person for this data. I called the BKK VBU hotline and was told to better write an email here https://www.meine-krankenkasse.de/kontaktformular/

Just to keep track of the communication and for later reference, I post this here:

> Sehr geehrte Damen und Herren,
> 
> Mein Name ist Tobias Zwick und ich arbeite an einer Software für die Abrechnung von Pflegedienstleistungen bei gesetzlichen Pflegekassen. Ich habe eine Frage die speziell die BKK VBU/West und Ost (und nur diese) betrifft, denn eine für BKK VBU/West und Ost hinterlegte Information zur Abrechnung ist eventuell fehlerhaft.
>
> Es geht um die sogenannte Kostenträgerdatei. Vom Ihrem Dachverband wird diese quartalsweise für alle Betriebskrankenkassen auf gkv-datenaustausch.de publiziert [1]. Diese enthält Informationen darüber, wie, wann, wohin und auf welche Art Rechnungen der Pflegedienstleister übermittelt werden sollen, die bei Ihnen versichert sind.
>
> Speziell geht es um die Datei BK05Q221.ke1 [2]. Die BKK VBU West und Ost sind in Zeile 4552 bis 4621 definiert. Hier gibt es nun folgendes Problem, das von unserem Parser als ungültig erkannt wird:
>
> Es sind mehrere Verknüpfungen dieser Art darin enthalten, hier z.B. Zeile 4566:
>
>  VKG+03+109723913+5++28++++55'
>
> Diese Verknüpfung hat übersetzt ins deutsche folgenden Inhalt:
>
> "Die Institution mit dem Institutionskennzeichen 109723913 ist eine Datenannahmestelle für digitale Rechnungsdaten von sonstigen Leistungserbringern von nichtärztlichen Dialysesachleistungen. Die Datenannahmestelle hat die Befugnis, die verschlüsselten Rechnungsdaten zu entschlüsseln.
> Angenommen werden Rechnungen, Verordnungen und Kostenvoranschläge auf Papier."
>
> Hier scheint der letzte Satz dem Rest des Inhaltes zu widersprechen, denn Papier ist nicht digital und auch nicht verschlüsselt. Speziell geht es um den Schlüssel "28" in der oben genannten Zeile. Für die Datenlieferungsart "digital" müsste statt "28" der Schlüssel "07" verwendet werden. Wenn die Institution nicht Daten aktzeptiert, sondern Papier, dann müsste der Schlüssel "VKG+09" statt "VKG+03" verwendet werden - zumindest nach meinem Verständnis der Dokumentation.
>
> Vielleicht ist es ein Fehler in der Kostenträgerdatei, vielleicht ist es bloß ein Missverständnis und es handelt sich um einen Spezialfall, der nicht dokumentiert ist, aber von entsprechender Abrechnungssoftware abgedeckt werden muss.
>
> Ich würde mich freuen, dies mit dieser Email aufklären zu können und darüber Rückmeldung zu erhalten.
>
> Viele Grüße
> Tobias Zwick
>
>[1] https://gkv-datenaustausch.de/leistungserbringer/sonstige_leistungserbringer/kostentraegerdateien_sle/kostentraegerdateien.jsp
>
>[2] https://gkv-datenaustausch.de/media/dokumente/leistungserbringer_1/sonstige_leistungserbringer/kostentraegerdateien_1/BK05Q221.ke1

**Comment by westnordost** [comment]
I wrote a copy of this email also to the head of "Abteilung Datenmanagement, Empirie, IT" as seen here https://www.bkk-dachverband.de/bkk-dv/kontakt
as they are ultimately the publishers of this information.

**Comment by westnordost** [comment]
The head of IT at BKK Dachverband answered and said that it's not their department anymore but that of Bitmarck. So I wrote the same question to the contact here: https://services.bitmarck.de/welcome/index.php?id=5406

**Comment by westnordost** [comment]
Got an automatic reply with an assigned issue number from Bitmarck

```
Sehr geehrte Damen und Herren,

vielen Dank für Ihre E-Mail. Ihre Anfrage wird unter der Incident-Nummer #INC6153995 von einem unserer Fachbereiche bearbeitet.

HINWEIS: Diese Mail wurde automatisch erstellt. Bitte antworten Sie nicht direkt auf die Mail, sondern verwenden Sie hierfür den nachfolgenden Link.

mailto:servicedesk@bitmarck.de?subject=Kundenantwort%20fuer%20Incident:%20#INC6153995


Mit freundlichen Grüßen

BITMARCK 
Kruppstraße 64, 45145 Essen
Telefon             0800 BITMARCK (0800 2486 2725)
Telefax             0800 BITMARCKFAX (0800 2486 2725 329)
E-Mail              servicedesk@bitmarck.de
Internet           www.bitmarck.de
 
```

**Comment by westnordost** [comment]
Wow nice, already got an answer. It looks like indeed this was just a mistake in that Kostenträger file:

> vielen Dank für Ihre Nachricht.
> In der Kostenträgerdatei TP5 war tatsächlich ein Fehler enthalten.
> Diesen haben wir soeben korrigiert und die Kostenträgerdatei an den GKV-Spitzenverband zur Veröffentlichung gesendet.
> Die Kostenträgerdatei wird voraussichtlich im Laufe dieser Woche auf der Internetseite des GKV-Spitzenverbandes veröffentlicht.

**Comment by westnordost** [comment]
Weird though that no other consumer of those Kostenträger files (like all those commercial software) noticed that. Maybe they are even more lenient.

**Comment by westnordost** [comment]
I'll leave this issue open until after the new Kostenträger file has been updated, so I can confirm that the issue has been fixed.

**Comment by michaelkamphausen** [comment]
Good job! I am thrilled that our parser is able to detect this error.

**Comment by westnordost** [comment]
Confirmed, they fixed it. However, they fixed it in `BK05Q221.ke2`. So, fixed it in a file that is already valid since 01.04. This contradicts the statement in the documentation that new Kostenträger files only come in effect every quarter and must be published also one quarter before.

What this means for us, is, that we should expect that Kostenträger date could change (or at least be fixed) any time, so the job that pulls the current Kostenträger data one way or another should run more often than once a quarter, maybe daily even.
