### ISSUE TITLE
Clarify spurious Kostenträgerdatei data: Not specified who can decrypt data

### ISSUE THREAD

**Issue by westnordost** [coop-care/paid#28]
For at least one Kostenträger, I found, by chance, that it links to a data acceptance office that cannot decrypt the data, but seemingly also never defines which data acceptance office can decrypt it, i.e. using whose key it should be encrypted.

The one example I found was BARMER, so I contacted the person who was listed as contact person.

> Sehr geehrte Frau ...
> 
> Mein Name ist Tobias Zwick und ich arbeite an einer Software für die 
> Abrechnung von Pflegedienstleistungen bei gesetzlichen Pflegekassen.Ich 
> schreibe Ihnen, weil Sie in der Kostenträgerdatei EK06Q221.ke1 [1] als 
> Ansprechpartnerin für die BARMER (Institutionskennzeichen 184940005) 
> eingetragen sind.
> Es geht um einen möglichen Fehler in dieser Datei.
> 
> In Zeile 1553-1558 dieser Datei steht folgendes zur BARMER:
> 
> VKG+02+109989162+6++07+1+++02'
> VKG+02+109989162+6++07+1+++03'
> VKG+02+109989162+6++07+1+++04'
> VKG+02+109989162+6++07+1+++05'
> VKG+02+109989162+6++07+1+++07'
> VKG+02+109989162+6++07+1+++08'
> 
> Übersetzt in menschenlesbar, wird hier folgendes spezifiziert:
> 
> "Abrechnungen von Pflegedienstleistungen der Leistungsarten Tages-, 
> Nacht-, Kurzzeit-, vollstationärer und Verhinderungspflege, sowie 
> Zuschüsse nach § 43 Abs. 3 SGB XI sollen digital an die Institution mit 
> dem Institutionskennzeichen 109989162 (T-Systems International GmbH) 
> geschickt werden.
> T-Systems International GmbH selbst hat nicht die Befugnis, die 
> Abrechnungsdaten zu entschlüsseln."
> 
> Soweit so gut, der Dokumentation folgend fehlt jedoch offenbar die 
> Information, an wen die Abrechnungen denn verschlüsselt werden sollen. 
> Können Sie mir helfen, diese Sache aufzuklären?
> Wissen Sie, an wen diese Rechnungen verschlüsselt werden sollen?
> 
> Gruß
> Tobias Zwick
> 
> [1] 
> https://gkv-datenaustausch.de/media/dokumente/leistungserbringer_1/pflege/kostentraegerdateien_2/EK06Q221.ke1 
>

**Comment by westnordost** [comment]
Very likely a mistake by whoever wrote this into the Kostenträger file.

**Comment by westnordost** [comment]
Got an answer, asking if the question is not answered yet and she asked me to "supply a signture". I replied 

> Vielen Dank für die Antwort. Ich habe zwischenzeitlich keine Antwort 
> erhalten. Ich bin mich auch recht sicher, dass es sich tatsächlich um 
> einen Fehler in der Kostenträger-Datei handelt.
> 
> Nochmal zusammengefasst:
> 
> In Zeile 1553-1558 der Kostenträgerdatei EK06Q221.ke1 steht folgendes 
> zur BARMER:
> 
> VKG+02+109989162+6++07+1+++02'
> VKG+02+109989162+6++07+1+++03'
> VKG+02+109989162+6++07+1+++04'
> VKG+02+109989162+6++07+1+++05'
> VKG+02+109989162+6++07+1+++07'
> VKG+02+109989162+6++07+1+++08'
> 
> Übersetzt in menschenlesbar, wird hier folgendes spezifiziert:
> 
> "Abrechnungen von Pflegedienstleistungen der Leistungsarten Tages-,
> Nacht-, Kurzzeit-, vollstationärer und Verhinderungspflege, sowie
> Zuschüsse nach § 43 Abs. 3 SGB XI sollen digital an die Institution mit
> dem Institutionskennzeichen 109989162 (T-Systems International GmbH)
> geschickt werden.
> T-Systems International GmbH selbst hat nicht die Befugnis, die
> Abrechnungsdaten zu entschlüsseln."
> 
> Gleichzeitig fehlt hier jedoch die Angabe, an wen (an welche IK) die 
> Daten in diesem Fall verschlüsselt werden sollen. Sollen die Daten an 
> sie selbst (IK=184940005) verschlüsselt werden, scheinen hier die Einträge
> 
> VKG+03+184940005+6++07+1+++02'
> VKG+03+184940005+6++07+1+++03'
> VKG+03+184940005+6++07+1+++04'
> VKG+03+184940005+6++07+1+++05'
> VKG+03+184940005+6++07+1+++07'
> VKG+03+184940005+6++07+1+++08'
> 
> zu fehlen.
> 
> ---
> 
> Ich weiß nicht genau was Sie mit Signatur meinen, aber wenn Sie wissen 
> wollen aus welchem Kontext diese Anfrage kommt:
> 
> Ich arbeite als freiberuflicher Softwareentwickler an einer vom 
> Bundesministerium für Bildung und Forschung geförderten Open Source 
> Library, die Abrechnungen ggü. den GKV tätigen können soll. Als freie 
> Software kann diese dann nach Fertigstellung unentgeltlich von den 
> verschiedenen Pflegediensten eingesetzt werden.
> 
> Der Name der Library ist PAID ("Pflegeabrechnung in Deutschland") [1]
> 
> [1] https://prototypefund.de/en/project/paid/

**Comment by westnordost** [comment]
I noticed that I found this possible mistake only by chance. There is no validator for this. Maybe I should add this too. Who knows for how many institution this information is missing.

On the other hand, I should wait for their answer. Maybe I err in thinking they err and/or there is a reasonable way to interpret/infer this apparently missing data somehow.

**Comment by westnordost** [comment]
Got a reply that said that she willl try to find out if this is really an error in the Kostenträger but she persisted that I give her the data for the company I work for. 
I gave her what can be seen on the imprint on coopcare.de

**Comment by michaelkamphausen** [comment]
Okay, good. I am wondering why this might be important to her.

**Comment by westnordost** [comment]
No answer yet, I asked again. (And noted that I'll be on vacation in the next ~2 weeks).

Probably not surprising that those institutions that **do** have mistakes in their kostenträger stuff are also those that tend to not understand / are unresponsive to mistakes being reported.

**Comment by westnordost** [comment]
The contact person apologizes for the long wait for the answer and wrote this:

> Wie Sie bereits richtig eingeschätzt haben, erfolgt nur eine Verknüpfung zu einem Rechenzentrum ohne Entschlüsselungsbefugnis (hier: T-Systems). Die für die Durchführung des produktiven Datenaustauschs notwendige Verknüpfung zu einem Rechenzentrum mit Entschlüsselungsbefugnis fehlt. Zum jetzigen Zeitpunkt wird das Datenaustauschverfahren zu den Leistungsarten 02 bis 08 noch nicht aktiv umgesetzt. Ein Update zu der Kostenträgerdatei erfolgt erst, wenn feststeht an welches Rechenzentrum die Daten gehen sollen. Leider kann ich Ihnen kein konkretes Datum hierfür benennen. 

In other words: "Right, so this doesn't work until we fixed this. We don't know when we fixed this".

So, we now know that this is a mistake on the side of those who created the Kostenträger data and not a misunderstanding or similar. I guess this resolves this ticket then.
